//Authors : Emma Hilborn(200282755),
//          Alex Friesen(200302342),
//          Dan Masci(200299037),
//          Karen Springford(200299681)

//Class : Enterprise Computing
//Semester : 4
//Professor : Tom Tsiliopolous
//Purpose : Final Team Project - E-Commerce Store
//Website Name : EzGames3.azurewebsites.net/Menu
//This is the page containing our store's sample data
//their appropriate categories (Platform).
//ALL IMAGES TAKEN FROM EBGAMES WEBSITE

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace Comp2007_Project2.Models
{
    public class SampleData : DropCreateDatabaseIfModelChanges<StoreEntities>
    {
        protected override void Seed(StoreEntities context)
        {
            var platforms = new List<Platform>
            {
                new Platform { Name = "XBox One" },
                new Platform { Name = "PS4" },
                new Platform { Name = "3DS" }
            };

            var labels = new List<Label>
            {
                new Label { Name = "" },
                new Label { Name = "Popular" },
                new Label { Name = "Pre-Order" },
                new Label { Name = "New Release" }
            };

            new List<Game>
            {

                new Game { Name = "Halo Wars 2", ShortDescription = "Taking place where Halo 5 left off, enjoy 13 brand new campaigns unravelling a whole new story!", FullDescription = "Taking place where Halo 5 left off, enjoy 13 brand new campaigns unravelling a whole new story! With a new enemy threatening the universe, the Spirit of Fire's crew must stand between humanity and an Armaggedon! Lead armies of various fighting races, from Spartans to Warthogs in this RTS!", Price = 79.99M, Rating = "M", ReleaseDate = Convert.ToDateTime("2017-02-21"), ImageFullUrl ="/Assets/images/store/HaloWarsFull.jpg", ImageIconUrl ="/Assets/images/store/HaloWarsIcon.jpg", Platform = platforms.Single(p => p.Name == "XBox One"), Label = labels.Single(l => l.Name == "Pre-Order") },
                new Game { Name = "Tom Clancy's The Division", ShortDescription = "Do you have what it takes to be a member of The Division and save a city?", FullDescription = "Do you have what it takes to be a member of The Division and save a city? In this RPG that uses a modern military setting for the first time, fight as an agent of The Division to take back New York from a mass pandemic outbreak!", Price = 79.99M, Rating = "M", ReleaseDate = Convert.ToDateTime("2016-03-08"), ImageFullUrl ="/Assets/images/store/TheDivisionFull.jpg", ImageIconUrl ="/Assets/images/store/TheDivisionIcon.jpg", Platform = platforms.Single(p => p.Name == "XBox One"), Label = labels.Single(l => l.Name == "New Release") },
                new Game { Name = "ReCore", ShortDescription = "As one of few humans alive, you must join forces with robot companions...", FullDescription="As one of few humans alive, you must join forces with robot companions to take the planet back from robot foes. Finding yourself alone after being in cryo-sleep for years, the future of New Eden rests on your shoulders. Can you save mankind?", Price = 49.99M, Rating = "T", ReleaseDate = Convert.ToDateTime("2016-09-13"), ImageFullUrl ="/Assets/images/store/RecoreFull.jpg", ImageIconUrl ="/Assets/images/store/RecoreIcon.jpg", Platform = platforms.Single(p => p.Name == "XBox One"), Label = labels.Single(l => l.Name == "Pre-Order") },
                new Game { Name = "Mirror's Edge Catalyst", ShortDescription = "In the elegant city of Glass, follow Faith as she fights for freedom, exposing the dark secrets hidden in the city's walls.", FullDescription = "In the elegant city of Glass, follow Faith as she fights for freedom, exposing the dark secrets hidden in the city's walls. Rebel against the government to as you find yourself swept into the political turmoil that sleeps beneath the pristine landscape.", Price = 49.99M, Rating = "T", ReleaseDate = Convert.ToDateTime("2016-06-07"), ImageFullUrl ="/Assets/images/store/MirrorsEdgeFull.jpg", ImageIconUrl ="/Assets/images/store/MirrorsEdgeIcon.jpg", Platform = platforms.Single(p => p.Name == "XBox One"), Label = labels.Single(l => l.Name == "New Release") },
                new Game { Name = "Overwatch (Origins Edition)", ShortDescription = "Choose a hero, join a team, and get ready to battle it out on the field!", FullDescription = "Choose a hero (from a wide range of options), join a team, and get ready to battle it out on the field! After decades of peace have ended and warfare rises again, heroes like you must rise to the challenge! Whether you're a soldier, scientist, adventurer, or another oddball, Overwatch needs you!", Price = 79.99M, Rating = "T", ReleaseDate = Convert.ToDateTime("2016-05-24"), ImageFullUrl ="/Assets/images/store/OverwatchFull.jpg", ImageIconUrl ="/Assets/images/store/OverwatchIcon.jpg", Platform = platforms.Single(p => p.Name == "XBox One"), Label = labels.Single(l => l.Name == "Popular") },
                new Game { Name = "Monopoly", ShortDescription = "Enjoy the classic game of Monopoly...", FullDescription="Enjoy the classic game of Monopoly, but set in a beautiful 3D world! Plus, play online with up to 6 players! A perfect edition to any family game night!", Price = 19.99M, Rating = "E", ReleaseDate = Convert.ToDateTime("2014-11-18"), ImageFullUrl ="/Assets/images/store/MonopolyFull.jpg", ImageIconUrl ="/Assets/images/store/MonopolyIcon.jpg", Platform = platforms.Single(p => p.Name == "XBox One"), Label = labels.Single(l => l.Name == "") },
                new Game { Name = "Trackmania Turbo", ShortDescription = "Put the pedal to the metal of your matchbox car on any of over 200 tracks, with 4 backgrounds!", FullDescription="Put the pedal to the metal of your matchbox car on any of over 200 tracks, with 4 backgrounds! Play the game arcade-style or create your own crazy tracks to race! You can play this for ages and find something new every time!", Price = 29.99M, Rating = "E", ReleaseDate = Convert.ToDateTime("2016-03-22"), ImageFullUrl ="/Assets/images/store/TrackmaniaFull.jpg", ImageIconUrl ="/Assets/images/store/TrackmaniaIcon.jpg", Platform = platforms.Single(p => p.Name == "XBox One"), Label = labels.Single(l => l.Name == "") },
                new Game { Name = "Forza Motorsport 6", ShortDescription = "Race to your heart's content in over 450 Forzavista cars.", FullDescription = "Race to your heart's content in over 450 Forzavista cars. The most realistic racing sim out there where everything from wind to rain affects your driving conditions! If you get tired of racing alone, no problem - you can hop into multiplayer races online!", Price = 59.99M, Rating = "E", ReleaseDate = Convert.ToDateTime("2015-09-15"), ImageFullUrl ="/Assets/images/store/Forza6Full.jpg", ImageIconUrl ="/Assets/images/store/Forza6Icon.jpg", Platform = platforms.Single(p => p.Name == "XBox One"), Label = labels.Single(l => l.Name == "") },
                new Game { Name = "Battleborn", ShortDescription= "What kind of hero were YOU born to be? Samurai vampire? Cyborg hawkman?", FullDescription = "What kind of hero were YOU born to be? Samurai vampire? Cyborg hawkman? No matter what, we've got you covered! Make use of many types of heroes and weapons to protect the last star in the universe in this next-gen shooter by the creators of Borderlands!", Price = 39.99M, Rating = "T", ReleaseDate = Convert.ToDateTime("2015-12-31"), ImageFullUrl ="/Assets/images/store/BattlebornFull.jpg", ImageIconUrl ="/Assets/images/store/BattlebornIcon.jpg", Platform = platforms.Single(p => p.Name == "XBox One"), Label = labels.Single(l => l.Name == "") },
                new Game { Name = "No Man's Sky", ShortDescription = "In No Man's Sky, embark on a journey through an infinite universe of over 18 quintillion planets. Survive, explore, and travel to undiscovered lands!", FullDescription = "In No Man's Sky, embark on a journey through an infinite universe of over 18 quintillion planets. Survive, explore, and travel to undiscovered lands! You'll never run out of things to do in this world so large even the developers haven't explored it all!", Price = 79.99M, Rating = "T", ReleaseDate = Convert.ToDateTime("2016-08-09"), ImageFullUrl ="/Assets/images/store/NoMansSkyFull.jpg", ImageIconUrl ="/Assets/images/store/NoMansSkyIcon.jpg", Platform = platforms.Single(p => p.Name == "PS4"), Label = labels.Single(l => l.Name == "New Release") },
                new Game { Name = "Attack on Titan", ShortDescription = "Based on the popular manga and anime, follow the story of Attack on Titan's main characters...", FullDescription = "Based on the popular manga and anime, follow the story of Attack on Titan's main characters through the anime's first season's events! Play as many different characters, from Eren to Mikasa to Levi! Pre-order for bonus costumes!", Price = 69.99M, Rating = "RP", ReleaseDate = Convert.ToDateTime("2016-08-30"), ImageFullUrl ="/Assets/images/store/AotFull.jpg", ImageIconUrl ="/Assets/images/store/AotIcon.jpg", Platform = platforms.Single(p => p.Name == "PS4"), Label = labels.Single(l => l.Name == "Pre-Order") },
                new Game { Name = "Fairy Fencer F: Advent Dark Force", ShortDescription = "Enjoy 'Fairy Fencer F' remastered in HD on PS4!", FullDescription = "Enjoy 'Fairy Fencer F' remastered in HD on PS4! Change your outcome and the game's ending based on what choices you make as you play! 3 paths to play, 3 game modes, and 3 new character routes have been added in this version!", Price = 79.99M, Rating = "T", ReleaseDate = Convert.ToDateTime("2016-07-26"), ImageFullUrl ="/Assets/images/store/FairyFencerFull.jpg", ImageIconUrl ="/Assets/images/store/FairyFencerIcon.jpg", Platform = platforms.Single(p => p.Name == "PS4"), Label = labels.Single(l => l.Name == "New Release") },
                new Game { Name = "LEGO Star Wars: The Force Awakens", ShortDescription = "Re-experience the tale of 'The Force Awakens' as game set in an all-LEGO world!", FullDescription = "Re-experience the tale of 'The Force Awakens' as game set in an all-LEGO world! The game also includes bonus tales/gameplay set between Return of the Jedi and The Force Awakens.", Price = 69.99M, Rating = "RP", ReleaseDate = Convert.ToDateTime("2016-06-28"), ImageFullUrl ="/Assets/images/store/StarWarsFull.jpg", ImageIconUrl ="/Assets/images/store/StarWarsIcon.jpg", Platform = platforms.Single(p => p.Name == "PS4"), Label = labels.Single(l => l.Name == "Popular") },
                new Game { Name = "Uncharted 4: A Thief's End", ShortDescription = "Taking place years after his latest adventure, Nathan Drake is forced to return to thievery.", FullDescription = "Taking place years after his latest adventure, Nathan Drake is forced to return to thievery. Tempted by a promise of adventure, and a plea for help, he will undergo a long journey if he hopes to save his brother. Can you find Captain Henry Avery's long-lost treasure?", Price = 79.99M, Rating = "RP", ReleaseDate = Convert.ToDateTime("2016-05-10"), ImageFullUrl ="/Assets/images/store/UnchartedFull.jpg", ImageIconUrl ="/Assets/images/store/UnchartedIcon.jpg", Platform = platforms.Single(p => p.Name == "PS4"), Label = labels.Single(l => l.Name == "") },
                new Game { Name = "Sword Art Online: Lost Song", ShortDescription = "Based on the anime Sword Art Online, delve into the world of ALfheim Online...", FullDescription = "Based on the anime Sword Art Online, delve into the world of ALfheim Online alongside the anime's protagonist, Kirito! Will you be able to beat Svart ALFheim first, or will the mysterious Shamrock guild finish the expansion first?", Price = 69.99M, Rating = "T", ReleaseDate = Convert.ToDateTime("2015-11-17"), ImageFullUrl ="/Assets/images/store/SaoFull.jpg", ImageIconUrl ="/Assets/images/store/SaoIcon.jpg", Platform = platforms.Single(p => p.Name == "PS4"), Label = labels.Single(l => l.Name == "") },
                new Game { Name = "Tales of Zestiria", ShortDescription = "Follow the story of curious protagonist Sorey, who shoulders the burden of becoming the Shepherd.", FullDescription = "Follow the story of curious protagonist Sorey, who shoulders the burden of becoming the Shepherd. Gather a team of comrades to save the land from darkness. Can you overcome the darkness hidden in the human heart?", Price = 39.99M, Rating = "T", ReleaseDate = Convert.ToDateTime("2015-10-20"), ImageFullUrl ="/Assets/images/store/ZestiriaFull.jpg", ImageIconUrl ="/Assets/images/store/ZestiriaIcon.jpg", Platform = platforms.Single(p => p.Name == "PS4"), Label = labels.Single(l => l.Name == "Popular") },
                new Game { Name = "ShovelKnight", ShortDescription = "Take on perilous foes with no more than a shovel!", FullDescription = "Take on perilous foes with no more than a shovel! Enjoy the 8-bit land of the Shovel Knight as you follow the code of Shovelry! How far can you make it with such a seemingly simple weapon?", Price = 29.99M, Rating = "E", ReleaseDate = Convert.ToDateTime("2015-11-03"), ImageFullUrl ="/Assets/images/store/ShovelKnightFull.jpg", ImageIconUrl ="/Assets/images/store/ShovelKnightIcon.jpg", Platform = platforms.Single(p => p.Name == "PS4"), Label = labels.Single(l => l.Name == "") },
                new Game { Name = "Final Fantasy XV", ShortDescription = "Play as Noctis, a Prince travelling to wed his fiancé, when unexpected political turmoil arises.", FullDescription = "Play as Noctis, a Prince travelling to wed his fiancé, when unexpected political turmoil arises. His simple journey turns struggle as his homeland is overtaken by a neighboring empire. Can you take it back?", Price = 79.99M, Rating = "T", ReleaseDate = Convert.ToDateTime("2016-09-30"), ImageFullUrl ="/Assets/images/store/FfxvFull.jpg", ImageIconUrl ="/Assets/images/store/FfxvIcon.jpg", Platform = platforms.Single(p => p.Name == "PS4"), Label = labels.Single(l => l.Name == "Pre-Order") },
                new Game { Name = "Pokémon Sun", ShortDescription = "Celebrate 20 years since Japan's release of Pokémon Red and Green by buying Pokémon Sun - one of the latest games in the series!", FullDescription = "Celebrate 20 years since Japan's release of Pokémon Red and Green by buying Pokémon Sun - one of the latest games in the series! Discover new Pokémon, and old Pokémon in their new Alolan forms! Pokémon Sun's legendary is Solgaleo.", Price = 49.99M, Rating = "RP", ReleaseDate = Convert.ToDateTime("2016-11-18"), ImageFullUrl ="/Assets/images/store/PkmnSunFull.jpg", ImageIconUrl ="/Assets/images/store/PkmnSunIcon.jpg", Platform = platforms.Single(p => p.Name == "3DS"), Label = labels.Single(l => l.Name == "Pre-Order") },
                new Game { Name = "Pokémon Moon", ShortDescription = "Celebrate 20 years since Japan's release of Pokémon Red and Green by buying Pokémon Moon - one of the latest games in the series!", FullDescription = "Celebrate 20 years since Japan's release of Pokémon Red and Green by buying Pokémon Moon - one of the latest games in the series! Discover new Pokémon, and old Pokémon in their new Alolan forms! Pokémon Moon's legendary is Lunala.", Price = 49.99M, Rating = "RP", ReleaseDate = Convert.ToDateTime("2016-11-18"), ImageFullUrl ="/Assets/images/store/PkmnMoonFull.jpg", ImageIconUrl ="/Assets/images/store/PkmnMoonIcon.jpg", Platform = platforms.Single(p => p.Name == "3DS"), Label = labels.Single(l => l.Name == "Pre-Order") },
                new Game { Name = "Monster Hunter Generations", ShortDescription = "Take on new monsters in new locations, all while utilizing new game mechanics in the latest game from the popular Monster Hunter series!", FullDescription = "Take on new monsters in new locations, all while utilizing new game mechanics in the latest game from the popular Monster Hunter series! With the introduction of Hunting Styles and Hunter Arts, you can completely customize your hunting style to play in a way that suits you! Join up to 3 other hunters in multiplayer modes!", Price = 49.99M, Rating = "T", ReleaseDate = Convert.ToDateTime("2016-07-15"), ImageFullUrl ="/Assets/images/store/MonsterHunterFull.jpg", ImageIconUrl ="/Assets/images/store/MonsterHunterIcon.jpg", Platform = platforms.Single(p => p.Name == "3DS"), Label = labels.Single(l => l.Name == "Popular") },
                new Game { Name = "Zero Time Dilemma", ShortDescription = "When nine participates find themselves trapped in a facility, forced to play deadly games to escape, you will have to answer the question: who lives, and who dies?", FullDescription = "When nine participates find themselves trapped in a facility, forced to play deadly games to escape, you will have to answer the question: who lives, and who dies? As the third entry in the Zero Escape series, you'll find yourself faced with more puzzles and passwords in this even-harder 'Decision Game'.", Price = 49.99M, Rating = "M", ReleaseDate = Convert.ToDateTime("2016-05-28"), ImageFullUrl ="/Assets/images/store/ZeroFull.jpg", ImageIconUrl ="/Assets/images/store/ZeroIcon.jpg", Platform = platforms.Single(p => p.Name == "3DS"), Label = labels.Single(l => l.Name == "") },
                new Game { Name = "Disney Art Academy", ShortDescription = "Bring our YOUR inner artist as you use lessons from real Disney art and Pixar animations...", FullDescription = "Bring our YOUR inner artist as you use lessons from real Disney art and Pixar animations to recreate over 80 Disney and Pixar characters! It doesn't matter if you're a beginner or a pro - you can join the fun!", Price = 39.99M, Rating = "RP", ReleaseDate = Convert.ToDateTime("2016-05-13"), ImageFullUrl ="/Assets/images/store/DisneyArtFull.jpg", ImageIconUrl ="/Assets/images/store/DisneyArtIcon.jpg", Platform = platforms.Single(p => p.Name == "3DS"), Label = labels.Single(l => l.Name == "") },
                new Game { Name = "LEGO Star Wars: The Force Awakens", ShortDescription = "Re-experience the tale of 'The Force Awakens' as game set in an all-LEGO world!", FullDescription = "Re-experience the tale of 'The Force Awakens' as game set in an all-LEGO world! The game also includes bonus tales/gameplay set between Return of the Jedi and The Force Awakens.", Price = 34.99M, Rating = "RP", ReleaseDate = Convert.ToDateTime("2016-06-28"), ImageFullUrl ="/Assets/images/store/StarWars3dsFull.jpg", ImageIconUrl ="/Assets/images/store/StarWars3dsIcon.jpg", Platform = platforms.Single(p => p.Name == "3DS"), Label = labels.Single(l => l.Name == "New Release") }
            }.ForEach(a => context.Games.Add(a));

        }
    }
}